-- MySQL Script generated by MySQL Workbench
-- Tue Oct  1 18:34:30 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema odbcviajes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema odbcviajes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `odbcviajes` DEFAULT CHARACTER SET utf8 ;
USE `odbcviajes` ;

-- -----------------------------------------------------
-- Table `odbcviajes`.`cancelacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `odbcviajes`.`cancelacion` ;

CREATE TABLE IF NOT EXISTS `odbcviajes`.`cancelacion` (
  `idCancelacion` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL DEFAULT NULL,
  `montoReintegro` FLOAT NOT NULL,
  PRIMARY KEY (`idCancelacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `odbcviajes`.`ciudad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `odbcviajes`.`ciudad` ;

CREATE TABLE IF NOT EXISTS `odbcviajes`.`ciudad` (
  `idCiudad` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `latitud` VARCHAR(45) NOT NULL,
  `longitud` VARCHAR(45) NOT NULL,
  `baja` TINYINT(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`idCiudad`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `odbcviajes`.`pasajero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `odbcviajes`.`pasajero` ;

CREATE TABLE IF NOT EXISTS `odbcviajes`.`pasajero` (
  `DNI` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `millas` FLOAT NULL DEFAULT NULL,
  `clave` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `nacionalidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `odbcviajes`.`pasaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `odbcviajes`.`pasaje` ;

CREATE TABLE IF NOT EXISTS `odbcviajes`.`pasaje` (
  `codigo` VARCHAR(10) NOT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `valor` FLOAT NOT NULL,
  `pasajero` INT(11) NOT NULL,
  `origen` INT(11) NOT NULL,
  `destino` INT(11) NOT NULL,
  `formaPago` ENUM('dinero', 'millas') NULL DEFAULT NULL,
  `cancelacion` INT(11) NULL DEFAULT NULL,
  `millas` FLOAT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_Pasaje_Pasajero_idx` (`pasajero` ASC),
  INDEX `fk_Pasaje_Destinos1_idx` (`origen` ASC),
  INDEX `fk_Pasaje_Destinos2_idx` (`destino` ASC),
  INDEX `fk_Pasaje_Cancelacion1_idx` (`cancelacion` ASC),
  CONSTRAINT `fk_Pasaje_Cancelacion1`
    FOREIGN KEY (`cancelacion`)
    REFERENCES `odbcviajes`.`cancelacion` (`idCancelacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pasaje_Destinos1`
    FOREIGN KEY (`origen`)
    REFERENCES `odbcviajes`.`ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pasaje_Destinos2`
    FOREIGN KEY (`destino`)
    REFERENCES `odbcviajes`.`ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pasaje_Pasajero`
    FOREIGN KEY (`pasajero`)
    REFERENCES `odbcviajes`.`pasajero` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `odbcviajes`.`configMillas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `odbcviajes`.`configMillas` ;

CREATE TABLE IF NOT EXISTS `odbcviajes`.`configMillas` (
  `precioMilla` FLOAT NOT NULL,
  `millaXKilometro` FLOAT NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
